server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/barber_booking
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: DevelopmentKey_256Bits_Long_Enough_For_Now_1234567890!@#
jwt:
  secret: DevelopmentKey_256Bits_Long_Enough_For_Now_1234567890!@#
  expiration: 86400000